name: astanahublmss
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  akar_icons_flutter: ^1.1.21
  confetti: ^0.7.0
  flutter:
    sdk: flutter
  flutter_side_menu: ^0.4.0
  flutter_svg: ^2.0.10+1
  path_provider: ^2.1.3
  url_launcher: ^6.2.6
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/
    - assets/svg/
    - assets/ui/
    - assets/ui/for_who/
  uses-material-design: true
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
